name: "modbus-proxy"
description: "Proxy for Accessing modbus systems. Allows multiple client connections"
version: "1.0.18"
slug: "modbus_proxy"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
url: "https://community.home-assistant.io/t/updated-solaredge-modbus-full-setup-guide-with-energy-dashboard-integration-for-installations-with-battery-connected/340956/216?u=akulatraxas"
startup: services
init: false
options:
  upstreamhost: "192.168.x.x"
  upstreamport: 502
  listenport: 503
  connection_time: 0.1
  timeout: 10
  loglevel: "INFO"
schema:
  upstreamhost: str
  upstreamport: int
  listenport: int
  connection_time: float
  timeout: int
  loglevel: list(INFO|DEBUG|ERROR)
ports:
  503/tcp: 503
